services:
  web:
    depends_on:
      - db
    image: uonlearningtech/examsys-php-apache:${EXAMSYS_DOCKER_PHP}
    volumes:
     - "${EXAMSYS_DOCKER_WWWROOT}:/var/www/html"
  mail:
    image: dockage/mailcatcher
    ports:
      - "${EXAMSYS_DOCKER_MAIL_PORT}:1080"
