version: '3'
services:
  php:
    build: .
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - db
     - cache
     - calc
    volumes:
     - "${ROGO_DOCKER_WWWROOT}:/var/www"
  db:
   image: mysql:5.6
   environment:
     MYSQL_ROOT_PASSWORD: ${ROGO_DOCKER_MYSQLROOT}
  cache:
   image: memcached:1.5
  calc:
   image: stevenpollack/docker-rserve